pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - cp -r ./.well-known/test/index.html public/.well-known/test/index.html
  artifacts:
    paths:
    - public
  only:
  - master