pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - mkdir -p public/.well-known/acme-challenge/
  - cp a9mzgWJ_P7L3dO7hogYcVIM3VnVPeLi8hD1KdEVRYzo public/.well-known/acme-challenge/
  artifacts:
    paths:
    - public
  only:
  - master